{{ if not .Values.job.enabled }}
{{- $pvcUsingTemplate := and .Values.persistence.enabled .Values.statefulSet.enabled (not .Values.persistence.existingClaim) (ne .Values.persistence.accessMode "ReadWriteMany")| ternary true false }}
---
apiVersion: apps/v1
{{- if .Values.statefulSet.enabled }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "nim-llm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nim-llm.selectorLabels" . | nindent 6 }}
      {{- if .Values.model.labels }}
      {{- toYaml .Values.model.labels | nindent 6 }}
      {{- end }}
  {{- if .Values.statefulSet.enabled }}
  serviceName: {{ include "nim-llm.fullname" . }}
  podManagementPolicy: "Parallel"
  {{- end }}
  {{ include "nim-llm.nim-pod-spec" . | nindent 2 }}
  {{- if $pvcUsingTemplate }}
  {{- with .Values.persistence.stsPersistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .whenDeleted }}
    whenScaled: {{ .whenScaled }}
  {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: model-store
      labels:
        {{- include "nim-llm.labels" . | nindent 8 }}
      {{- with .Values.persistence.annotations  }}
      annotations:
        {{ toYaml . | indent 4 }}
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
  {{- end }}
{{- end }}