apiVersion: v1
kind: Pod
metadata:
  name: triton
  labels:
    app: triton
spec:
  containers:
  - name: triton
    image: nvcr.io/nvidia/tritonserver:24.04-py3-sdk
    command: ["sleep", "infinity"]
