apiVersion: batch/v1
kind: Job
metadata:
  name: load-files-nv-ingest
  namespace: aira
spec:
  template:
    spec:
      imagePullSecrets:
      - name: ngc-secret
      containers:
      - name: load-files-nv-ingest
        image: nvcr.io/nvidia/blueprint/aira-load-files:v1.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MILVUS_HOST
          value: "milvus.rag.svc.cluster.local"
        - name: MILVUS_PORT
          value: "19530"
        - name: RAG_INGEST_URL
          value: "http://ingestor-server.rag.svc.cluster.local:8082"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: tempdata
          mountPath: /tmp-data
      volumes:
      - name: tempdata
        emptyDir: {}

      restartPolicy: OnFailure 