apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: milvus-standalone
  namespace: rag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/instance: rag
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - rag
