---
# ServiceMonitor for Reranking NIM
# Scrapes metrics from the reranking NIM service for Azure Monitor Prometheus
apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rag-reranking-nim
  namespace: rag
spec:
  endpoints:
  - interval: 30s
    path: /v1/metrics
    port: http
  namespaceSelector:
    matchNames:
    - rag
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-nim-llama-32-nv-rerankqa-1b-v2
