apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: llama-3-1-70b-instruct-2xgpu
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-llama-3.1-70b-instruct
      resources:
        limits:
          nvidia.com/gpu: "2"
        requests:
          nvidia.com/gpu: "2"
      runtime: nvidia-nim-llama-3.1-70b-instruct-1.1.0
      storageUri: pvc://nvidia-nim-pvc/
