apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: llama3-8b-instruct-2xh100
spec:
  predictor:
    minReplicas: 1
    model:
      modelFormat:
        name: nvidia-nim-llama3-8b-instruct
      resources:
        limits:
          nvidia.com/gpu: "2"
        requests:
          nvidia.com/gpu: "2"
      runtime: nvidia-nim-llama3-8b-instruct-1.0.0
      storageUri: pvc://nvidia-nim-pvc/
    nodeSelector:
      nvidia.com/gpu.product: NVIDIA-H100-SXM4-80GB
