FROM ubuntu:22.04
EXPOSE 3333
RUN apt-get update && apt-get install curl -y
RUN apt-get update && apt-get install python3-pip -y
RUN pip install fastapi
RUN pip install "uvicorn[standard]"
COPY source/query.sh /usr/local/bin/query.sh
COPY source/http_respond.py  /home/nemo/http_respond.py
RUN chmod +x /usr/local/bin/query.sh
ENV CLOUD_RUN_ENDPOINT_URL=https://llama-3-8b-instruct-kcifu7ad4a-uc.a.run.app
RUN echo CLOUD_RUN_ENDPOINT_URL $CLOUD_RUN_ENDPOINT_URL
ENTRYPOINT ["/usr/local/bin/query.sh"]


