apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-llama
  labels:
    app: nim-llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nim-llama
  template:
    metadata:
      labels:
        app: nim-llama
    spec:
      containers:
        - name: nim
          image: nvcr.io/nim/meta/llama3-8b-instruct:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nim-secret
                  key: NGC_API_KEY
      imagePullSecrets:
        - name: registry-secret
