apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: llama-3.3-nemotron-super-49b-v1_2xgpu_1.8.2
spec:
  annotations:
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8000"
    serving.kserve.io/enable-metric-aggregation: "true"
    serving.kserve.io/enable-prometheus-scraping: "true"
  containers:
  - env:
    - name: NIM_CACHE_PATH
      value: /opt/nim/.cache
    - name: HF_TOKEN
      valueFrom:
        secretKeyRef:
          name: nvidia-nim-secrets
          key: HF_TOKEN
    - name: NGC_API_KEY
      valueFrom:
        secretKeyRef:
          name: nvidia-nim-secrets
          key: NGC_API_KEY
    image: nvcr.io/nim/nvidia/llama-3.3-nemotron-super-49b-v1:1.8.2
    name: kserve-container
    ports:
    - containerPort: 8000
      protocol: TCP
    resources:
      limits:
        cpu: "12"
        memory: 256Gi
      requests:
        cpu: "12"
        memory: 256Gi
    volumeMounts:
    - mountPath: /opt/nim/.cache
      name: dshm
  imagePullSecrets:
  - name: ngc-secret
  protocolVersions:
  - v2
  - grpc-v2
  supportedModelFormats:
  - autoSelect: true
    name: nvidia-nim-llama-nemotron-3.3-49b
    priority: 1
    version: "1.8.2"
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: 500Gi
    name: dshm
