job:
  enabled: true
csi:
  enabled: false
customCommand: ["/bin/bash", "-c", "download-to-cache && find $NIM_CACHE_PATH -type d -printf '%P\\n' | xargs -P 100 -I {} mkdir -p /upload-dir/{} && find $NIM_CACHE_PATH -type f,l -printf '%P\\n' | xargs -P 100 -I {} cp --no-dereference $NIM_CACHE_PATH/{} /upload-dir/{}"]
extraVolumes:
  cache-volume:
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: "ngc-gcs-cache"
        mountOptions: "max-conns-per-host=0"
extraVolumeMounts:
  cache-volume:
    mountPath: /upload-dir
    readOnly: false