---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.existingClaim | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- if .Values.persistence.mountOptions }}
  mountOptions:
    - {{ .Values.persistence.mountOptions | quote }}
{{- end }}
{{- if .Values.persistence.csi }}
  csi:
    driver: "{{ .Values.persistence.csi.driver }}"
    volumeHandle: "{{ .Values.persistence.csi.volumeHandle }}"
    readOnly: {{ .Values.persistence.csi.readOnly }}
{{- end }}
