---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts-configmap
  labels:
    {{- include "nim-llm.labels" . | nindent 4 }}
data:
  ngc_pull.sh: |-
{{ .Files.Get "files/ngc_pull.sh" | indent 4 }}
