---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scratch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: "premium-rwo"
