
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scratch-rwo
parameters:
  type: pd-ssd
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - read_ahead_kb=8192
