{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-aira-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: aira-frontend
  template:
    metadata:
      labels:
        app: aira-frontend
    spec:
      imagePullSecrets:
        - name: {{ .Values.ngcImagePullSecretName }}
      containers:
        - name: aira-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: INFERENCE_ORIGIN
              value: {{ .Values.frontend.proxyUrl }}
{{- end }}