apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: nim-on-gke
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: NVIDIA NIM™ on GKE
    source:
      repo: https://github.com/sujituk/nim-deploy
      sourceType: git
      dir: /test-infra-mgr/cloud-service-providers/google-cloud/gke
    actuationTool:
      flavor: Terraform
    description: {}
  content: {}
  interfaces:
    variables:
      - name: acknowledge
        varType: bool
        required: true
      - name: additional_labels
        description: Additional labels to add to Kubernetes resources.
        varType: string
        defaultValue: "created-by=gke-ai-quick-start-solutions,ai.gke.io=nim"
      - name: solution_deployment_view
        varType: bool
        required: true
      - name: cluster_location
        varType: string
        required: true
        defaultValue: "us-central1"
      - name: cluster_name
        varType: string
        defaultValue: "nim-demo-gke"
      - name: create_network
        description: Create the VPC specified by network_name/subnetwork_name
        varType: bool
        defaultValue: true
      - name: enable_gpu
        varType: bool
        defaultValue: true
      - name: network_name
        varType: string
        required: true
        defaultValue: "nim-demo-vpc"
      - name: project_id
        description: GCP project id
        varType: string
        required: true
      - name: subnetwork_cidr
        varType: string
        defaultValue: "10.100.0.0/16"
      - name: subnetwork_name
        varType: string
        required: true
        defaultValue: "nim-demo-subnet"
      - name: subnetwork_region
        varType: string
        defaultValue: "us-central1"
      - name: registry_server
        varType: string
        required: true
        defaultValue: "nvcr.io"
      - name: ngc_username
        varType: string
        required: true
        defaultValue: "$oauthtoken"
      - name: ngc_api_key
        varType: string
        required: true
        defaultValue: "$oauthtoken"
      - name: repository
        description: "Docker image of NIM container"
        varType: string
        required: true
        defaultValue: ""
      - name: model_name
        description: "Name of the NIM model"
        varType: string
        required: true
        defaultValue: ""
      - name: tag
        description: "Docker repository tag of NIM container"
        varType: string
        required: true
        defaultValue: ""
      - name: gpu_limits
        description: "GPU limits"
        varType: number
        defaultValue: 1
    outputs:
      - name: cluster_name
        description: GKE cluster name where the NIMs are running
      - name: cluster_location
        description: GKE cluster location
      - name: project_id
        description: GCP project
      - name: endpoint
        description: GKE cluster endpoint
