apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: nim-on-gke
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: NVIDIA NIM™ on GKE
    source:
      repo: https://github.com/NVIDIA/nim-deploy
      sourceType: git
      dir: /test-infra-mgr/cloud-service-providers/google-cloud/gke
    actuationTool:
      flavor: Terraform
    description: {}
  content: {}
  interfaces:
    variables:
      - name: acknowledge
        varType: bool
        required: true
      - name: additional_labels
        description: Additional labels to add to Kubernetes resources.
        varType: string
        defaultValue: "created-by=gke-ai-quick-start-solutions,ai.gke.io=nim"
      #- name: cluster_location
      #  varType: string
      #  required: true
      #  defaultValue: "us-central1"
      - name: cluster_name
        varType: string
        defaultValue: "nim-on-gke"
      - name: create_network
        description: Create the VPC specified by network_name/subnetwork_name
        varType: bool
        defaultValue: true
      - name: enable_gpu
        varType: bool
        defaultValue: true
      - name: goog_cm_deployment_name
        varType: string
        defaultValue: "nim-on-gke"        
      - name: kubernetes_namespace
        varType: string
        required: true
        defaultValue: "nim"
      - name: network_name
        varType: string
        required: true
        defaultValue: "vpc"
      - name: project_id
        description: GCP project id
        varType: string
        required: true
      - name: subnetwork_cidr
        varType: string
        defaultValue: "10.100.0.0/16"
      - name: subnetwork_name
        varType: string
        required: true
        defaultValue: "subnet"
      - name: ngc_username
        varType: string
        required: true
        defaultValue: "$oauthtoken"
      - name: ngc_api_key
        varType: string
        required: true
        defaultValue: ""
      - name: registry_server
        varType: string
        required: true
        #defaultValue: "nvcr.io"
        defaultValue: "us-docker.pkg.dev/nvidia-vgpu-public"
      - name: tag
        description: "Docker repository tag of NIM container"
        varType: string
        required: true
      - name: region_based_vm
        description: "Pick a region for GKE Cluster and NVIDIA GPU accelerator"
        varType: string
        required: true
        defaultValue: "L4 us-east4 g2-standard-24"
      - name: model_name
        description: "Pick a NIM model name"
        varType: string
        required: true
        defaultValue: ""
      - name: gpu_limits
        description: "GPU limits"
        varType: number
        defaultValue: 1
      - name: nim_license
        description: Terms and Conditions
        varType: bool
        defaultValue: false
        required: true
    outputs:
      - name: cluster_name
        description: GKE cluster name where the NIMs are running
      - name: cluster_location
        description: GKE cluster location
      - name: project_id
        description: GCP project
      - name: endpoint
        description: GKE cluster endpoint
