apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: nim-on-gke-display
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: NVIDIA NIM on GKE
    source:
      repo: https://github.com/sujituk/nim-deploy
      sourceType: git
      dir: /test-infra-mgr/cloud-service-providers/google-cloud/gke
  ui:
    input:
      variables:
        acknowledge:
          name: acknowledge
          title: Check to confirm you enabled Google APIs for your project with this command.
          section: acknowledge
          subtext: |
                  <pre>
                    <code style="background: #f4f4f4;border: 1px solid #ddd; border-left: 3px solid #3367d6; color: #6d6868; font-size: 12px; max-width: 100%; padding: 0.5em 0.5em; display: inline; line-height: 45px;">gcloud services enable serviceusage.googleapis.com cloudresourcemanager.googleapis.com</code>
                  </pre>
          enumValueLabels:
            - label: Confirm that all prerequisites have been met.
              value: "true"
        additional_labels:
          name: additional_labels
          title: Additional Labels
          invisible: true
          section: required_config
        solution_deployment_view:
          name: solution_deployment_view
          title: Check to confirm that upon deployment completion, you need to go to the Solution deployment page, find your deployment, and follow suggested next steps on the deployment DETAILS tab.
          section: acknowledge
          subtext: <p>
                    <a href="https://console.cloud.google.com/products/solutions/deployments"><i>Solution deployment page</i></a>
                   </p>
          enumValueLabels:
            - label: Confirm that all prerequisites have been met.
              value: "true"
        cluster_location:
          name: cluster_location
          title: Cluster Location
          section: required_config
          xGoogleProperty:
            type: ET_GCE_REGION
            # specified regions have L4, A2 and A3 GPUs https://cloud.google.com/compute/docs/gpus/gpu-regions-zones#view-using-tools
            gce_region:
              allowlisted_regions: ["asia-east1","asia-southeast1","europe-west1","europe-west4","us-central1","us-east1","us-east4","us-west1","us-west4"]
        cluster_name:
          name: cluster_name
          title: Cluster Name
          section: required_config
        create_network:
          name: create_network
          title: Create Network
          invisible: true
        enable_gpu:
          name: enable_gpu
          title: Enable GPU nodepool
          section: required_config
          invisible: true
        network_name:
          name: network_name
          title: Network Name
          invisible: true
        project_id:
          name: project_id
          title: Project Id
          invisible: true
        subnetwork_cidr:
          name: subnetwork_cidr
          title: SubNetwork CIDR
          invisible: true
        subnetwork_name:
          name: subnetwork_name
          title: SubNetwork Name
          invisible: true
        subnetwork_region:
          name: subnetwork_region
          title: SubNetwork Region
        registry_server:
          name: registry_server
          title: NVIDIA Registry
          section: required_config
        ngc_username:
          name: ngc_username
          title: NGC Login username
          section: required_config
          invisible: true
        ngc_api_key:
          name: ngc_api_key
          title: NGC API Key
          section: required_config
        repository:
          name: repository
          title: NIM Image
          section: required_config
        model_name:
          name: model_name
          title: NIM Model name
          section: required_config
        tag:
          name: tag
          title: NIM image tag
          section: required_config
        gpu_limits:
          name: gpu_limits
          title: GPU limits
          section: required_config
      sections:
        - name: acknowledge
          title: Before you begin
          subtext:
                This solution deploys a sample <a href="https://github.com/sujituk/nim-deploy/blob/add-ngc-pull-gcs/cloud-service-providers/google-cloud/gke/README.md#nvidia-nims-on-gke"><i>NVIDIA NIM</i></a> application on GKE in your project.</br>
        - name: required_config
          title: Required configuration
    runtime:
      outputMessage: Deployment can take several minutes to complete.
      suggestedActions:
        - heading: Connect to GKE Cluster
          description: Connect to GKE Cluster. Open another terminal and follow these <a href="https://github.com/sujituk/nim-deploy/blob/add-ngc-pull-gcs/cloud-service-providers/google-cloud/gke/README.md#inference">instructions</a> to run inference.
      outputs:
        cluster_name: {}
        cluster_location: {}
        project_id: {}
        endpoint: {}